{% set name = "types-tzlocal" %}
{% set version = "4.2.2.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-tzlocal-{{ version }}.tar.gz
  sha256: fe178f213d979bae032385265e76c5893e0c28d9c2ea32c0328346795024729d

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-pytz

test:
  commands:
    - test -f $SP_DIR/tzlocal-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for tzlocal
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
