{% set version = "5.1.0.1" %}

package:
  name: types-tzlocal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/t/types-tzlocal/types-tzlocal-{{ version }}.tar.gz
  sha256: b84a115c0c68f0d0fa9af1c57f0645eeef0e539147806faf1f95ac3ac01ce47b

build:
  number: 1
  noarch: python
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - types-pytz

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - test -f $SP_DIR/tzlocal-stubs/__init__.pyi

about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for tzlocal
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
