{% set name = "types-tzlocal" %}
{% set version = "5.1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/types-tzlocal-{{ version }}.tar.gz
  sha256: b84a115c0c68f0d0fa9af1c57f0645eeef0e539147806faf1f95ac3ac01ce47b

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - types-pytz

test:
  requires:
    - python {{ python_min }}
  commands:
    - test -f $SP_DIR/tzlocal-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for tzlocal
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
